---
- hosts: digital-ocean-vps
  tasks:

  - name: Update all system packages
    ansible.builtin.apt:
      name: "*"
      state: latest
    become: yes

  - name: Check for required reboot
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required

  - name: Reboot if required
    ansible.builtin.reboot:
    when: reboot_required.stat.exists == True
