---
# Installs packages needed for work desktop
# Copies autokey configuration into place using a handler if autokey-gtk is
# installed

# [todo] How are packages that require a repository installation handled?

- hosts: work-desktop
  tasks:

# Create one task to install a list of packages vs. repeating yourself?
  - name: Update apt, install latest version of autokey-gtk
    ansible.builtin.apt:
      name: autokey-gtk
      update_cache: yes # seems an update is required before packages are installed
      state: latest
    become: yes
    notify: Copy autokey configuration into place

  - name: Install latest version of copyq
    ansible.builtin.apt:
      name: copyq
      state: latest
    become: yes

  - name: Install latest version of keepassxc
    ansible.builtin.apt:
      name: keepassxc
      state: latest
    become: yes

  - name: Install latest version of piper
    ansible.builtin.apt:
      name: piper
      state: latest
    become: yes
    
  - name: Install latest version of vim
    ansible.builtin.apt:
      name: vim
      state: latest
    become: yes
    
  - name: Install latest version of tmux
    ansible.builtin.apt:
      name: tmux
      state: latest
    become: yes

  handlers:
    - name: Copy autokey configuration into place
      ansible.posix.synchronize:
        src: autokey-data/
        dest: ~/.config/autokey/
