---
# Installs packages needed for work desktop
# Copies autokey configuration into place using a handler if autokey-gtk is
# installed
# Usage: ansible-playbook -i hosts -u root main-playbook.yml
# May need to `ansible-galaxy collection install -r requirements.yml`

# [todo] How are packages that require a repository installation handled?

- hosts: localhost
  tasks:

  - name: Update apt, install latest version of autokey-gtk
    ansible.builtin.apt:
      name: autokey-gtk
      update_cache: yes # seems an update is required before packages are installed
      state: latest
    become: yes
    notify: Copy autokey configuration into place

  - name: Install latest version of packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: latest
    become: yes
    # TODO: figure out how to be conditional based on host being used (desktop vs. laptop)
    loop:
      - keepassxc
      - vim
      - tmux
      - copyq
      #- lutris # if laptop, don't install
      - gnome-tweak-tool # if ubuntu + gnome
      - tree
      - barrier
      - net-tools
      - curl
      - spotify
    community.general.snap:
      name:
        - spotify

  handlers:
  - name: Copy autokey configuration into place
    ansible.posix.synchronize:
      src: autokey-data/
      dest: ~/.config/autokey/
